// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMrY3sUEZrU5OkMFHzVYuLvqhu27ad_dI',
    appId: '1:115000064754:web:b1d767721bf1d94d95ee6b',
    messagingSenderId: '115000064754',
    projectId: 'the-void-oceanv2',
    authDomain: 'the-void-oceanv2.firebaseapp.com',
    storageBucket: 'the-void-oceanv2.firebasestorage.app',
    measurementId: 'G-0MXSK8TF32',
    databaseURL: 'https://the-void-oceanv2-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBMgZW-_UAJyR6DTZMOkbnESQcbNNtJTc',
    appId: '1:115000064754:android:b745e2a4e939659f95ee6b',
    messagingSenderId: '115000064754',
    projectId: 'the-void-oceanv2',
    storageBucket: 'the-void-oceanv2.firebasestorage.app',
    databaseURL: 'https://the-void-oceanv2-default-rtdb.firebaseio.com',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCedbc76KPSSIJ6GcyN13_btuQVg-Ipua0',
    appId: '1:115000064754:ios:e6cde3361671636d95ee6b',
    messagingSenderId: '115000064754',
    projectId: 'the-void-oceanv2',
    storageBucket: 'the-void-oceanv2.firebasestorage.app',
    iosBundleId: 'com.example.ocean',
    databaseURL: 'https://the-void-oceanv2-default-rtdb.firebaseio.com',
  );
}
